# Default values for unifi-dns-sync.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: ghcr.io/moellere/unifi-dns-sync
  pullPolicy: Always
  # Overrides the image tag whose default is the chart appVersion.
  tag: "latest"

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

syncIntervalSeconds: 3600

# List of controllers
# Example:
# controllers:
#   - host: "10.250.6.1"
#     port: 443
#     username: "admin"
#     password: "password"
#     site: "default"
#     verify_ssl: false
controllers: []

resources: {}
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}
