apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "unifi-dns-sync.fullname" . }}-config
  labels:
    {{- include "unifi-dns-sync.labels" . | nindent 4 }}
data:
  SYNC_INTERVAL_SECONDS: {{ .Values.syncIntervalSeconds | quote }}
