{{- if and .Values.gateway.enabled .Values.gateway.create -}}
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: {{ include "unifi-dns-sync.fullname" . }}
  labels:
    {{- include "unifi-dns-sync.labels" . | nindent 4 }}
spec:
  gatewayClassName: {{ .Values.gateway.className | default "traefik" }}
  listeners:
    - name: http
      port: 80
      protocol: HTTP
      allowedRoutes:
        namespaces:
          from: Same
{{- end }}
