apiVersion: v1
kind: Secret
metadata:
  name: {{ include "unifi-dns-sync.fullname" . }}-credentials
  labels:
    {{- include "unifi-dns-sync.labels" . | nindent 4 }}
type: Opaque
stringData:
  controllers.json: {{ .Values.controllers | toJson | quote }}
