{{- if .Values.webUi.enabled -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "unifi-dns-sync.fullname" . }}-web
  labels:
    {{- include "unifi-dns-sync.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webUi.service.type }}
  ports:
    - port: {{ .Values.webUi.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "unifi-dns-sync.selectorLabels" . | nindent 4 }}
{{- end }}
